openapi: 3.0.0
info:
  description: Description of the Organization API
  title: Organization API
  version: 1.0.0
servers:
- description: Anypoint Cloudhub
  url: https://anypoint.mulesoft.com/accounts/api/
- description: Anypoint Cloudhub EU
  url: https://eu1.anypoint.mulesoft.com/accounts/api/
- description: Anypoint Cloudhub GOV
  url: https://gov.anypoint.mulesoft.com/accounts/api/
security:
- bearerAuth: []
paths:
  /organizations:
    post:
      description: Creates a new Business Group within an organization. This action
        can only be performed with an access token generated from user/pwd.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BGPostReqBody'
        description: Business Group Request Body Object
        required: true
      responses:
        "401":
          description: Access token is missing or invalid
        "400":
          content:
            text/html:
              schema:
                example: Organization Name provided is empty
                title: the error message
                type: string
          description: Bad request response
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BGCore'
          description: Success response
      summary: Creates a new Business Group within an organization.
  /organizations/{orgId}:
    delete:
      description: Delete a Business Group by its given id.
      parameters:
      - description: The organization Id
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "401":
          description: Access token is missing or invalid
        "204":
          content:
            application/json:
              schema:
                default: {}
                type: object
          description: Success response
      summary: Delete a Business Group by its id.
    get:
      description: Returns the Business Group with the given id
      parameters:
      - description: The organization Id
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "401":
          description: Access token is missing or invalid
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/masterBGDetail'
          description: Success response
      summary: Returns the business Group instance with the given id.
    put:
      description: Put a Business Group by its given id.
      parameters:
      - description: The organization Id
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BGPutReqBody'
        description: Business Group Request Body Object
        required: true
      responses:
        "401":
          description: Access token is missing or invalid
        "204":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BGCore'
          description: Success response
      summary: Put a Business Group by its id.
components:
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    BadRequestError:
      content:
        text/html:
          schema:
            example: Organization Name provided is empty
            title: the error message
            type: string
      description: Bad request response
    SuccessGetBG:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/masterBGDetail'
      description: Success response
    SuccessPostBG:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BGCore'
      description: Success response
    SuccessDeleteBG:
      content:
        application/json:
          schema:
            default: {}
            type: object
      description: Success response
    SuccessPutBG:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BGCore'
      description: Success response
  schemas:
    BGPostReqBody:
      example:
        entitlements:
          globalDeployment: false
          staticIps:
            reassigned: 5
            assigned: 4
          createSubOrgs: false
          loadBalancer:
            reassigned: 2
            assigned: 5
          vpns:
            reassigned: 6
            assigned: 6
          vCoresSandbox:
            reassigned: 6.965117697638846
            assigned: 3.5571952270680973
          vCoresProduction:
            reassigned: 6.438423552598547
            assigned: 9.018348186070783
          createEnvironments: false
          vCoresDesign:
            reassigned: 8.762042012749001
            assigned: 6.683562403749608
          vpcs:
            reassigned: 2
            assigned: 1
        name: name
        ownerId: ownerId
        parentOrganizationId: parentOrganizationId
      properties:
        entitlements:
          $ref: '#/components/schemas/entitlementsCore'
        name:
          default: ""
          description: An explanation about the purpose of this instance.
          title: name
          type: string
        ownerId:
          default: ""
          description: An explanation about the purpose of this instance.
          title: ownerId
          type: string
        parentOrganizationId:
          default: ""
          description: An explanation about the purpose of this instance.
          title: parentOrganizationId
          type: string
      required:
      - entitlements
      - name
      - ownerId
      - parentOrganizationId
      title: BGPostReqBody
      type: object
    BGPutReqBody:
      example:
        entitlements:
          globalDeployment: false
          staticIps:
            reassigned: 5
            assigned: 4
          createSubOrgs: false
          loadBalancer:
            reassigned: 2
            assigned: 5
          vpns:
            reassigned: 6
            assigned: 6
          vCoresSandbox:
            reassigned: 6.965117697638846
            assigned: 3.5571952270680973
          vCoresProduction:
            reassigned: 6.438423552598547
            assigned: 9.018348186070783
          createEnvironments: false
          vCoresDesign:
            reassigned: 8.762042012749001
            assigned: 6.683562403749608
          vpcs:
            reassigned: 2
            assigned: 1
        name: name
        sessionTimeout: 0
        ownerId: ownerId
      properties:
        entitlements:
          $ref: '#/components/schemas/entitlementsCore'
        name:
          default: ""
          description: An explanation about the purpose of this instance.
          title: name
          type: string
        ownerId:
          default: ""
          description: An explanation about the purpose of this instance.
          title: ownerId
          type: string
        sessionTimeout:
          default: 0
          description: An explanation about the purpose of this instance.
          title: sessionTimeout
          type: integer
      title: BGPutReqBody
      type: object
    BGCore:
      example:
        entitlements:
          workerLoggingOverride:
            enabled: false
          globalDeployment: false
          crowd:
            environments: false
            hideApiManagerDesigner: false
            hideFormerApiPlatform: false
          monitoringCenter:
            productSKU: 9
          objectStoreKeys:
            addOn: 1
            base: 1
          workerClouds:
            reassigned: 6
            assigned: 5
          vCoresDesign:
            reassigned: 8.762042012749001
            assigned: 6.683562403749608
          vpcs:
            reassigned: 2
            assigned: 1
          gateways:
            assigned: 5
          appViz: false
          apiCommunityManager:
            enabled: false
          hybridInsight: false
          apiQuery:
            productSKU: 1
            enabled: false
          objectStoreRequestUnits:
            addOn: 1
            base: 6
          messaging:
            assigned: 7
          tradingPartnersProduction:
            assigned: 9
          angGovernance:
            level: 0
          anypointSecurityTokenization:
            enabled: false
          hybrid:
            enabled: false
          apis:
            enabled: false
          staticIps:
            reassigned: 5
            assigned: 4
          runtimeFabricCloud:
            enabled: false
          kpiDashboard:
            enabled: false
          autoscaling: false
          partnersSandbox:
            assigned: 1
          externalIdentity: false
          hybridAutoDiscoverProperties: false
          vpns:
            reassigned: 6
            assigned: 6
          runtimeFabric: false
          serviceMesh:
            enabled: false
          cam:
            enabled: false
          anypointSecurityEdgePolicies:
            enabled: false
          pcf: false
          armAlerts: false
          createSubOrgs: false
          loadBalancer:
            reassigned: 2
            assigned: 5
          mqMessages:
            addOn: 3
            base: 2
          vCoresSandbox:
            reassigned: 6.965117697638846
            assigned: 3.5571952270680973
          createEnvironments: false
          apiMonitoring:
            schedules: 6
          tradingPartnersSandbox:
            assigned: 9
          mqRequests:
            addOn: 4
            base: 7
          apiQueryC360:
            enabled: false
          partnersProduction:
            assigned: 7
          exchange2:
            enabled: false
          mqAdvancedFeatures:
            enabled: false
          vCoresProduction:
            reassigned: 6.438423552598547
            assigned: 9.018348186070783
          crowdSelfServiceMigration:
            enabled: false
          designCenter:
            api: false
            mozart: false
        isAutomaticAdminPromotionExempt: false
        owner:
          lastLogin: lastLogin
          lastName: lastName
          mfaVerifiersConfigured: mfaVerifiersConfigured
          type: type
          enabled: false
          mfaVerificationExcluded: false
          organizationId: organizationId
          createdAt: createdAt
          firstName: firstName
          deleted: false
          phoneNumber: phoneNumber
          id: id
          idprovider_id: idprovider_id
          email: email
          updatedAt: updatedAt
          username: username
        subOrganizationIds:
        - subOrganizationIds
        - subOrganizationIds
        clientId: "[\"1ab4bb7db66448be902379d1fcfb1a43\"]"
        environments:
        - organizationId: organizationId
          clientId: clientId
          isProduction: false
          name: name
          id: id
          type: type
        - organizationId: organizationId
          clientId: clientId
          isProduction: false
          name: name
          id: id
          type: type
        tenantOrganizationIds:
        - tenantOrganizationIds
        - tenantOrganizationIds
        ownerId: ownerId
        isFederated: false
        createdAt: "[\"2021-03-05T14:06:52.976Z\"]"
        isMaster: false
        domain: "[\"ms-04\"]"
        name: name
        id: id
        mfaRequired: mfaRequired
        idprovider_id: idprovider_id
        properties: "{}"
        parentOrganizationIds:
        - parentOrganizationIds
        - parentOrganizationIds
        updatedAt: updatedAt
      properties:
        clientId:
          default: ""
          description: An explanation about the purpose of this instance.
          example: "[\"1ab4bb7db66448be902379d1fcfb1a43\"]"
          title: clientId
          type: string
        createdAt:
          default: ""
          description: An explanation about the purpose of this instance.
          example: "[\"2021-03-05T14:06:52.976Z\"]"
          title: createdAt
          type: string
        domain:
          default: ""
          description: An explanation about the purpose of this instance.
          example: "[\"ms-04\"]"
          title: domain
          type: string
        entitlements:
          $ref: '#/components/schemas/entitlements'
        environments:
          default: []
          description: An explanation about the purpose of this instance.
          items:
            $ref: '#/components/schemas/environment'
          title: environments
          type: array
        id:
          default: ""
          description: An explanation about the purpose of this instance.
          title: id
          type: string
        idprovider_id:
          default: ""
          description: An explanation about the purpose of this instance.
          title: idprovider_id
          type: string
        isAutomaticAdminPromotionExempt:
          default: false
          description: An explanation about the purpose of this instance.
          title: isAutomaticAdminPromotionExempt
          type: boolean
        isFederated:
          default: false
          description: An explanation about the purpose of this instance.
          title: isFederated
          type: boolean
        isMaster:
          default: false
          description: An explanation about the purpose of this instance.
          title: isMaster
          type: boolean
        mfaRequired:
          default: ""
          description: An explanation about the purpose of this instance.
          title: mfaRequired
          type: string
        name:
          default: ""
          description: An explanation about the purpose of this instance.
          title: name
          type: string
        ownerId:
          default: ""
          description: An explanation about the purpose of this instance.
          title: ownerId
          type: string
        parentOrganizationIds:
          default: []
          description: An explanation about the purpose of this instance.
          items:
            title: parentOrganizationId
            type: string
          title: parentOrganizationIds
          type: array
        properties:
          default: {}
          description: An explanation about the purpose of this instance.
          title: properties
          type: object
        subOrganizationIds:
          default: []
          description: An explanation about the purpose of this instance.
          items:
            default: ""
            description: An explanation about the purpose of this instance.
            title: subOrganizationId
            type: string
          title: subOrganizationIds
          type: array
        tenantOrganizationIds:
          default: []
          description: An explanation about the purpose of this instance.
          items:
            title: tenantOrganizationId
            type: string
          title: tenantOrganizationIds
          type: array
        updatedAt:
          default: ""
          description: An explanation about the purpose of this instance.
          title: updatedAt
          type: string
        owner:
          $ref: '#/components/schemas/owner'
      title: BGCore
      type: object
    masterBGDetail:
      allOf:
      - $ref: '#/components/schemas/BGCore'
      - $ref: '#/components/schemas/masterBGSpecificDetails'
      title: masterBGDetail
    entitlements:
      description: An explanation about the purpose of this instance.
      example:
        workerLoggingOverride:
          enabled: false
        globalDeployment: false
        crowd:
          environments: false
          hideApiManagerDesigner: false
          hideFormerApiPlatform: false
        monitoringCenter:
          productSKU: 9
        objectStoreKeys:
          addOn: 1
          base: 1
        workerClouds:
          reassigned: 6
          assigned: 5
        vCoresDesign:
          reassigned: 8.762042012749001
          assigned: 6.683562403749608
        vpcs:
          reassigned: 2
          assigned: 1
        gateways:
          assigned: 5
        appViz: false
        apiCommunityManager:
          enabled: false
        hybridInsight: false
        apiQuery:
          productSKU: 1
          enabled: false
        objectStoreRequestUnits:
          addOn: 1
          base: 6
        messaging:
          assigned: 7
        tradingPartnersProduction:
          assigned: 9
        angGovernance:
          level: 0
        anypointSecurityTokenization:
          enabled: false
        hybrid:
          enabled: false
        apis:
          enabled: false
        staticIps:
          reassigned: 5
          assigned: 4
        runtimeFabricCloud:
          enabled: false
        kpiDashboard:
          enabled: false
        autoscaling: false
        partnersSandbox:
          assigned: 1
        externalIdentity: false
        hybridAutoDiscoverProperties: false
        vpns:
          reassigned: 6
          assigned: 6
        runtimeFabric: false
        serviceMesh:
          enabled: false
        cam:
          enabled: false
        anypointSecurityEdgePolicies:
          enabled: false
        pcf: false
        armAlerts: false
        createSubOrgs: false
        loadBalancer:
          reassigned: 2
          assigned: 5
        mqMessages:
          addOn: 3
          base: 2
        vCoresSandbox:
          reassigned: 6.965117697638846
          assigned: 3.5571952270680973
        createEnvironments: false
        apiMonitoring:
          schedules: 6
        tradingPartnersSandbox:
          assigned: 9
        mqRequests:
          addOn: 4
          base: 7
        apiQueryC360:
          enabled: false
        partnersProduction:
          assigned: 7
        exchange2:
          enabled: false
        mqAdvancedFeatures:
          enabled: false
        vCoresProduction:
          reassigned: 6.438423552598547
          assigned: 9.018348186070783
        crowdSelfServiceMigration:
          enabled: false
        designCenter:
          api: false
          mozart: false
      properties:
        angGovernance:
          $ref: '#/components/schemas/angGovernance'
        anypointSecurityEdgePolicies:
          $ref: '#/components/schemas/anypointSecurityEdgePolicies'
        anypointSecurityTokenization:
          $ref: '#/components/schemas/anypointSecurityTokenization'
        apiCommunityManager:
          $ref: '#/components/schemas/apiCommunityManager'
        apiMonitoring:
          $ref: '#/components/schemas/apiMonitoring'
        apiQuery:
          $ref: '#/components/schemas/apiQuery'
        apiQueryC360:
          $ref: '#/components/schemas/apiQueryC360'
        apis:
          $ref: '#/components/schemas/apis'
        appViz:
          default: false
          description: An explanation about the purpose of this instance.
          title: appViz
          type: boolean
        armAlerts:
          default: false
          description: An explanation about the purpose of this instance.
          title: armAlerts
          type: boolean
        autoscaling:
          default: false
          description: An explanation about the purpose of this instance.
          title: autoscaling
          type: boolean
        cam:
          $ref: '#/components/schemas/cam'
        createEnvironments:
          default: false
          description: An explanation about the purpose of this instance.
          title: createEnvironments
          type: boolean
        createSubOrgs:
          default: false
          description: An explanation about the purpose of this instance.
          title: createSubOrgs
          type: boolean
        crowd:
          $ref: '#/components/schemas/crowd'
        crowdSelfServiceMigration:
          $ref: '#/components/schemas/crowdSelfServiceMigration'
        designCenter:
          $ref: '#/components/schemas/The_designCenter_schema'
        exchange2:
          $ref: '#/components/schemas/exchange2'
        externalIdentity:
          default: false
          description: An explanation about the purpose of this instance.
          title: externalIdentity
          type: boolean
        gateways:
          $ref: '#/components/schemas/gateways'
        globalDeployment:
          default: false
          description: An explanation about the purpose of this instance.
          title: globalDeployment
          type: boolean
        hybrid:
          $ref: '#/components/schemas/The_hybrid_schema'
        hybridAutoDiscoverProperties:
          default: false
          description: An explanation about the purpose of this instance.
          title: hybridAutoDiscoverProperties
          type: boolean
        hybridInsight:
          default: false
          description: An explanation about the purpose of this instance.
          title: hybridInsight
          type: boolean
        kpiDashboard:
          $ref: '#/components/schemas/kpiDashboard'
        loadBalancer:
          $ref: '#/components/schemas/loadBalancer'
        messaging:
          $ref: '#/components/schemas/messaging'
        monitoringCenter:
          $ref: '#/components/schemas/monitoringCenter'
        mqAdvancedFeatures:
          $ref: '#/components/schemas/mqAdvancedFeatures'
        mqMessages:
          $ref: '#/components/schemas/mqMessages'
        mqRequests:
          $ref: '#/components/schemas/mqRequests'
        objectStoreKeys:
          $ref: '#/components/schemas/objectStoreKeys'
        objectStoreRequestUnits:
          $ref: '#/components/schemas/objectStoreRequestUnits'
        partnersProduction:
          $ref: '#/components/schemas/partnersProduction'
        partnersSandbox:
          $ref: '#/components/schemas/partnersSandbox'
        pcf:
          default: false
          description: An explanation about the purpose of this instance.
          title: pcf
          type: boolean
        runtimeFabric:
          default: false
          description: An explanation about the purpose of this instance.
          title: runtimeFabric
          type: boolean
        runtimeFabricCloud:
          $ref: '#/components/schemas/runtimeFabricCloud'
        serviceMesh:
          $ref: '#/components/schemas/serviceMesh'
        staticIps:
          $ref: '#/components/schemas/staticIps'
        tradingPartnersProduction:
          $ref: '#/components/schemas/tradingPartnersProduction'
        tradingPartnersSandbox:
          $ref: '#/components/schemas/tradingPartnersSandbox'
        vCoresDesign:
          $ref: '#/components/schemas/vCoresDesign'
        vCoresProduction:
          $ref: '#/components/schemas/vCoresProduction'
        vCoresSandbox:
          $ref: '#/components/schemas/vCoresSandbox'
        vpcs:
          $ref: '#/components/schemas/vpcs'
        vpns:
          $ref: '#/components/schemas/vpns'
        workerClouds:
          $ref: '#/components/schemas/workerClouds'
        workerLoggingOverride:
          $ref: '#/components/schemas/workerLoggingOverride'
      required:
      - createEnvironments
      - createSubOrgs
      - globalDeployment
      - loadBalancer
      - staticIps
      - vCoresDesign
      - vCoresProduction
      - vCoresSandbox
      - vpcs
      - vpns
      title: entitlements
      type: object
    entitlementsCore:
      description: An explanation about the purpose of this instance.
      example:
        globalDeployment: false
        staticIps:
          reassigned: 5
          assigned: 4
        createSubOrgs: false
        loadBalancer:
          reassigned: 2
          assigned: 5
        vpns:
          reassigned: 6
          assigned: 6
        vCoresSandbox:
          reassigned: 6.965117697638846
          assigned: 3.5571952270680973
        vCoresProduction:
          reassigned: 6.438423552598547
          assigned: 9.018348186070783
        createEnvironments: false
        vCoresDesign:
          reassigned: 8.762042012749001
          assigned: 6.683562403749608
        vpcs:
          reassigned: 2
          assigned: 1
      properties:
        globalDeployment:
          default: false
          description: An explanation about the purpose of this instance.
          title: globalDeployment
          type: boolean
        createEnvironments:
          default: false
          description: An explanation about the purpose of this instance.
          title: createEnvironments
          type: boolean
        createSubOrgs:
          default: false
          description: An explanation about the purpose of this instance.
          title: createSubOrgs
          type: boolean
        loadBalancer:
          $ref: '#/components/schemas/loadBalancer'
        staticIps:
          $ref: '#/components/schemas/staticIps'
        vCoresDesign:
          $ref: '#/components/schemas/vCoresDesign'
        vCoresProduction:
          $ref: '#/components/schemas/vCoresProduction'
        vCoresSandbox:
          $ref: '#/components/schemas/vCoresSandbox'
        vpcs:
          $ref: '#/components/schemas/vpcs'
        vpns:
          $ref: '#/components/schemas/vpns'
      required:
      - createEnvironments
      - createSubOrgs
      - globalDeployment
      - loadBalancer
      - staticIps
      - vCoresDesign
      - vCoresProduction
      - vCoresSandbox
      - vpcs
      - vpns
      title: entitlementsCore
      type: object
    environment:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        organizationId: organizationId
        clientId: clientId
        isProduction: false
        name: name
        id: id
        type: type
      properties:
        clientId:
          default: ""
          description: An explanation about the purpose of this instance.
          title: clientId
          type: string
        id:
          default: ""
          description: An explanation about the purpose of this instance.
          title: id
          type: string
        isProduction:
          default: false
          description: An explanation about the purpose of this instance.
          title: isProduction
          type: boolean
        name:
          default: ""
          description: An explanation about the purpose of this instance.
          title: name
          type: string
        organizationId:
          default: ""
          description: An explanation about the purpose of this instance.
          title: organizationId
          type: string
        type:
          default: ""
          description: An explanation about the purpose of this instance.
          title: type
          type: string
      required:
      - clientId
      - id
      - isProduction
      - name
      - organizationId
      - type
      title: environment
      type: object
    owner:
      example:
        lastLogin: lastLogin
        lastName: lastName
        mfaVerifiersConfigured: mfaVerifiersConfigured
        type: type
        enabled: false
        mfaVerificationExcluded: false
        organizationId: organizationId
        createdAt: createdAt
        firstName: firstName
        deleted: false
        phoneNumber: phoneNumber
        id: id
        idprovider_id: idprovider_id
        email: email
        updatedAt: updatedAt
        username: username
      properties:
        createdAt:
          default: ""
          description: An explanation about the purpose of this instance.
          title: createdAt
          type: string
        deleted:
          default: false
          description: An explanation about the purpose of this instance.
          title: deleted
          type: boolean
        email:
          default: ""
          description: An explanation about the purpose of this instance.
          title: The email schema
          type: string
        enabled:
          default: false
          description: An explanation about the purpose of this instance.
          title: enabled
          type: boolean
        firstName:
          default: ""
          description: An explanation about the purpose of this instance.
          title: firstName
          type: string
        id:
          default: ""
          description: An explanation about the purpose of this instance.
          title: id
          type: string
        idprovider_id:
          default: ""
          description: An explanation about the purpose of this instance.
          title: idprovider_id
          type: string
        lastLogin:
          default: ""
          description: An explanation about the purpose of this instance.
          title: lastLogin
          type: string
        lastName:
          default: ""
          description: An explanation about the purpose of this instance.
          title: lastName
          type: string
        mfaVerificationExcluded:
          default: false
          description: An explanation about the purpose of this instance.
          title: mfaVerificationExcluded
          type: boolean
        mfaVerifiersConfigured:
          default: ""
          description: An explanation about the purpose of this instance.
          title: mfaVerifiersConfigured
          type: string
        organizationId:
          default: ""
          description: An explanation about the purpose of this instance.
          title: organizationId
          type: string
        phoneNumber:
          default: ""
          description: An explanation about the purpose of this instance.
          title: phoneNumber
          type: string
        type:
          default: ""
          description: An explanation about the purpose of this instance.
          title: type
          type: string
        updatedAt:
          default: ""
          description: An explanation about the purpose of this instance.
          title: updatedAt
          type: string
        username:
          default: ""
          description: An explanation about the purpose of this instance.
          title: username
          type: string
      title: owner
      type: object
    subscription:
      description: An explanation about the purpose of this instance.
      properties:
        category:
          default: ""
          description: An explanation about the purpose of this instance.
          title: category
          type: string
        expiration:
          default: ""
          description: An explanation about the purpose of this instance.
          title: expiration
          type: string
        type:
          default: ""
          description: An explanation about the purpose of this instance.
          title: type
          type: string
      title: subscription
      type: object
      example: null
    masterBGSpecificDetails:
      properties:
        sessionTimeout:
          default: 0
          description: An explanation about the purpose of this instance.
          title: sessionTimeout
          type: integer
        subscription:
          $ref: '#/components/schemas/subscription'
      title: masterBGSpecificDetails
      type: object
      example: null
    angGovernance:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        level: 0
      properties:
        level:
          default: 0
          description: An explanation about the purpose of this instance.
          title: level
          type: integer
      required:
      - level
      title: angGovernance
      type: object
    anypointSecurityEdgePolicies:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        enabled: false
      properties:
        enabled:
          default: false
          description: An explanation about the purpose of this instance.
          title: enabled
          type: boolean
      required:
      - enabled
      title: anypointSecurityEdgePolicies
      type: object
    anypointSecurityTokenization:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        enabled: false
      properties:
        enabled:
          default: false
          description: An explanation about the purpose of this instance.
          title: enabled
          type: boolean
      required:
      - enabled
      title: anypointSecurityTokenization
      type: object
    apiCommunityManager:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        enabled: false
      properties:
        enabled:
          default: false
          description: An explanation about the purpose of this instance.
          title: enabled
          type: boolean
      required:
      - enabled
      title: apiCommunityManager
      type: object
    apiMonitoring:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        schedules: 6
      properties:
        schedules:
          default: 0
          description: An explanation about the purpose of this instance.
          title: schedules
          type: integer
      required:
      - schedules
      title: apiMonitoring
      type: object
    apiQuery:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        productSKU: 1
        enabled: false
      properties:
        enabled:
          default: false
          description: An explanation about the purpose of this instance.
          title: enabled
          type: boolean
        productSKU:
          default: 0
          description: An explanation about the purpose of this instance.
          title: productSKU
          type: integer
      required:
      - enabled
      title: apiQuery
      type: object
    apiQueryC360:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        enabled: false
      properties:
        enabled:
          default: false
          description: An explanation about the purpose of this instance.
          title: enabled
          type: boolean
      required:
      - enabled
      title: apiQueryC360
      type: object
    apis:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        enabled: false
      properties:
        enabled:
          default: false
          description: An explanation about the purpose of this instance.
          title: enabled
          type: boolean
      required:
      - enabled
      title: apis
      type: object
    cam:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        enabled: false
      properties:
        enabled:
          default: false
          description: An explanation about the purpose of this instance.
          title: enabled
          type: boolean
      required:
      - enabled
      title: cam
      type: object
    crowd:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        environments: false
        hideApiManagerDesigner: false
        hideFormerApiPlatform: false
      properties:
        environments:
          default: false
          description: An explanation about the purpose of this instance.
          title: environments
          type: boolean
        hideApiManagerDesigner:
          default: false
          description: An explanation about the purpose of this instance.
          title: hideApiManagerDesigner
          type: boolean
        hideFormerApiPlatform:
          default: false
          description: An explanation about the purpose of this instance.
          title: hideFormerApiPlatform
          type: boolean
      required:
      - environments
      - hideApiManagerDesigner
      - hideFormerApiPlatform
      title: crowd
      type: object
    crowdSelfServiceMigration:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        enabled: false
      properties:
        enabled:
          default: false
          description: An explanation about the purpose of this instance.
          title: enabled
          type: boolean
      required:
      - enabled
      title: crowdSelfServiceMigration
      type: object
    The_designCenter_schema:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        api: false
        mozart: false
      properties:
        api:
          default: false
          description: An explanation about the purpose of this instance.
          title: api
          type: boolean
        mozart:
          default: false
          description: An explanation about the purpose of this instance.
          title: mozart
          type: boolean
      title: The designCenter schema
      type: object
    exchange2:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        enabled: false
      properties:
        enabled:
          default: false
          description: An explanation about the purpose of this instance.
          title: enabled
          type: boolean
      required:
      - enabled
      title: exchange2
      type: object
    gateways:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        assigned: 5
      properties:
        assigned:
          default: 0
          description: An explanation about the purpose of this instance.
          title: assigned
          type: integer
      required:
      - assigned
      title: gateways
      type: object
    The_hybrid_schema:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        enabled: false
      properties:
        enabled:
          default: false
          description: An explanation about the purpose of this instance.
          title: enabled
          type: boolean
      required:
      - enabled
      title: The hybrid schema
      type: object
    kpiDashboard:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        enabled: false
      properties:
        enabled:
          default: false
          description: An explanation about the purpose of this instance.
          title: enabled
          type: boolean
      required:
      - enabled
      title: kpiDashboard
      type: object
    loadBalancer:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        reassigned: 2
        assigned: 5
      properties:
        assigned:
          default: 0
          description: An explanation about the purpose of this instance.
          title: assigned
          type: integer
        reassigned:
          default: 0
          description: An explanation about the purpose of this instance.
          title: reassigned
          type: integer
      required:
      - assigned
      title: loadBalancer
      type: object
    messaging:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        assigned: 7
      properties:
        assigned:
          default: 0
          description: An explanation about the purpose of this instance.
          title: assigned
          type: integer
      required:
      - assigned
      title: messaging
      type: object
    monitoringCenter:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        productSKU: 9
      properties:
        productSKU:
          default: 0
          description: An explanation about the purpose of this instance.
          title: productSKU
          type: integer
      required:
      - productSKU
      title: monitoringCenter
      type: object
    mqAdvancedFeatures:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        enabled: false
      properties:
        enabled:
          default: false
          description: An explanation about the purpose of this instance.
          title: enabled
          type: boolean
      required:
      - enabled
      title: mqAdvancedFeatures
      type: object
    mqMessages:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        addOn: 3
        base: 2
      properties:
        addOn:
          default: 0
          description: An explanation about the purpose of this instance.
          title: addOn
          type: integer
        base:
          default: 0
          description: An explanation about the purpose of this instance.
          title: base
          type: integer
      title: mqMessages
      type: object
    mqRequests:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        addOn: 4
        base: 7
      properties:
        addOn:
          default: 0
          description: An explanation about the purpose of this instance.
          title: addOn
          type: integer
        base:
          default: 0
          description: An explanation about the purpose of this instance.
          title: base
          type: integer
      title: mqRequests
      type: object
    objectStoreKeys:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        addOn: 1
        base: 1
      properties:
        addOn:
          default: 0
          description: An explanation about the purpose of this instance.
          title: addOn
          type: integer
        base:
          default: 0
          description: An explanation about the purpose of this instance.
          title: base
          type: integer
      title: objectStoreKeys
      type: object
    objectStoreRequestUnits:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        addOn: 1
        base: 6
      properties:
        addOn:
          default: 0
          description: An explanation about the purpose of this instance.
          title: addOn
          type: integer
        base:
          default: 0
          description: An explanation about the purpose of this instance.
          title: base
          type: integer
      title: objectStoreRequestUnits
      type: object
    partnersProduction:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        assigned: 7
      properties:
        assigned:
          default: 0
          description: An explanation about the purpose of this instance.
          title: assigned
          type: integer
      required:
      - assigned
      title: partnersProduction
      type: object
    partnersSandbox:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        assigned: 1
      properties:
        assigned:
          default: 0
          description: An explanation about the purpose of this instance.
          title: assigned
          type: integer
      required:
      - assigned
      title: partnersSandbox
      type: object
    runtimeFabricCloud:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        enabled: false
      properties:
        enabled:
          default: false
          description: An explanation about the purpose of this instance.
          title: enabled
          type: boolean
      required:
      - enabled
      title: runtimeFabricCloud
      type: object
    serviceMesh:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        enabled: false
      properties:
        enabled:
          default: false
          description: An explanation about the purpose of this instance.
          title: enabled
          type: boolean
      required:
      - enabled
      title: serviceMesh
      type: object
    staticIps:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        reassigned: 5
        assigned: 4
      properties:
        assigned:
          default: 0
          description: An explanation about the purpose of this instance.
          title: assigned
          type: integer
        reassigned:
          default: 0
          description: An explanation about the purpose of this instance.
          title: reassigned
          type: integer
      required:
      - assigned
      title: staticIps
      type: object
    tradingPartnersProduction:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        assigned: 9
      properties:
        assigned:
          default: 0
          description: An explanation about the purpose of this instance.
          title: assigned
          type: integer
      required:
      - assigned
      title: tradingPartnersProduction
      type: object
    tradingPartnersSandbox:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        assigned: 9
      properties:
        assigned:
          default: 0
          description: An explanation about the purpose of this instance.
          title: assigned
          type: integer
      required:
      - assigned
      title: tradingPartnersSandbox
      type: object
    vCoresDesign:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        reassigned: 8.762042012749001
        assigned: 6.683562403749608
      properties:
        assigned:
          default: 0
          description: An explanation about the purpose of this instance.
          title: assigned
          type: number
        reassigned:
          default: 0.0
          description: An explanation about the purpose of this instance.
          title: reassigned
          type: number
      required:
      - assigned
      title: vCoresDesign
      type: object
    vCoresProduction:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        reassigned: 6.438423552598547
        assigned: 9.018348186070783
      properties:
        assigned:
          default: 0
          description: An explanation about the purpose of this instance.
          title: assigned
          type: number
        reassigned:
          default: 0.0
          description: An explanation about the purpose of this instance.
          title: reassigned
          type: number
      required:
      - assigned
      title: vCoresProduction
      type: object
    vCoresSandbox:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        reassigned: 6.965117697638846
        assigned: 3.5571952270680973
      properties:
        assigned:
          default: 0
          description: An explanation about the purpose of this instance.
          title: assigned
          type: number
        reassigned:
          default: 0.0
          description: An explanation about the purpose of this instance.
          title: reassigned
          type: number
      required:
      - assigned
      title: vCoresSandbox
      type: object
    vpcs:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        reassigned: 2
        assigned: 1
      properties:
        assigned:
          default: 0
          description: An explanation about the purpose of this instance.
          title: assigned
          type: integer
        reassigned:
          default: 0
          description: An explanation about the purpose of this instance.
          title: reassigned
          type: integer
      required:
      - assigned
      title: vpcs
      type: object
    vpns:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        reassigned: 6
        assigned: 6
      properties:
        assigned:
          default: 0
          description: An explanation about the purpose of this instance.
          title: assigned
          type: integer
        reassigned:
          default: 0
          description: An explanation about the purpose of this instance.
          title: reassigned
          type: integer
      required:
      - assigned
      title: vpns
      type: object
    workerClouds:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        reassigned: 6
        assigned: 5
      properties:
        assigned:
          default: 0
          description: An explanation about the purpose of this instance.
          title: assigned
          type: integer
        reassigned:
          default: 0
          description: An explanation about the purpose of this instance.
          title: reassigned
          type: integer
      required:
      - assigned
      title: workerClouds
      type: object
    workerLoggingOverride:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        enabled: false
      properties:
        enabled:
          default: false
          description: An explanation about the purpose of this instance.
          title: enabled
          type: boolean
      required:
      - enabled
      title: workerLoggingOverride
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
